pull_requests:
  do_not_increment_build_number: true
build:
  verbosity: minimal
  publish_nuget: true
artifacts:
  - path: '**\*.nupkg'
cache:
  - packages -> **\packages.config
build_script:
- cmd: >-
    dotnet restore

    dotnet build
deploy:
- provider: NuGet
  api_key:
    secure: 96GhxtmD79trmOMd7lU5p1fzp/ZGfZHTFSyxjP4CvUf5dc3zMEdZ1ztxjF5Pue6L
  on:
    branch: master
  artifact: /.*\.nupkg/

skip_non_tags: true
